/*
Proyecto Capstone: Analisis Exploratorio de Datos (EDA) en PostgreSQL
Archivo: estructura.sql

Proposito:
  Crear un modelo relacional de e-commerce, cargar un dataset ficticio y dejarlo
  listo para las consultas de analisis incluidas en analisis.sql.

Creacion opcional de la base de datos:
  CREATE DATABASE capstone_project;

CREATE DATABASE debe ejecutarse conectado a otra base (por ejemplo, postgres)
y fuera de un bloque de transaccion. Despues, conectese a capstone_project y
ejecute el resto de este archivo. En pgAdmin, tambien puede crear la base desde
Databases > Create > Database y luego abrir Query Tool sobre ella.
*/

-- El orden inverso de dependencias permite repetir el script sin conflictos.
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;

CREATE TABLE clientes (
    cliente_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo  VARCHAR(120) NOT NULL,
    email            VARCHAR(150) NOT NULL UNIQUE,
    telefono         VARCHAR(25),
    ciudad           VARCHAR(80),
    fecha_registro   DATE NOT NULL,
    activo           BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_clientes_email_formato CHECK (POSITION('@' IN email) > 1)
);

CREATE TABLE productos (
    producto_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto  VARCHAR(120) NOT NULL UNIQUE,
    categoria        VARCHAR(60) NOT NULL,
    precio_lista     NUMERIC(12, 2) NOT NULL,
    costo_unitario   NUMERIC(12, 2) NOT NULL,
    activo           BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_productos_precio_positivo CHECK (precio_lista > 0),
    CONSTRAINT chk_productos_costo_no_negativo CHECK (costo_unitario >= 0),
    CONSTRAINT chk_productos_margen_posible CHECK (costo_unitario <= precio_lista)
);

CREATE TABLE pedidos (
    pedido_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id       INTEGER NOT NULL,
    fecha_pedido     TIMESTAMP NOT NULL,
    estado           VARCHAR(20) NOT NULL,
    canal_venta      VARCHAR(20) NOT NULL,
    descuento_pedido NUMERIC(5, 2),
    fecha_entrega    DATE,
    CONSTRAINT fk_pedidos_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes (cliente_id),
    CONSTRAINT chk_pedidos_estado
        CHECK (estado IN ('completado', 'enviado', 'cancelado')),
    CONSTRAINT chk_pedidos_canal
        CHECK (canal_venta IN ('web', 'app', 'marketplace')),
    CONSTRAINT chk_pedidos_descuento
        CHECK (descuento_pedido IS NULL OR descuento_pedido BETWEEN 0 AND 100),
    CONSTRAINT chk_pedidos_fecha_entrega
        CHECK (fecha_entrega IS NULL OR fecha_entrega >= fecha_pedido::DATE)
);

CREATE TABLE detalle_pedido (
    detalle_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        INTEGER NOT NULL,
    producto_id      INTEGER NOT NULL,
    cantidad         INTEGER NOT NULL,
    precio_unitario  NUMERIC(12, 2) NOT NULL,
    descuento_linea  NUMERIC(5, 2),
    CONSTRAINT fk_detalle_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos (pedido_id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (producto_id) REFERENCES productos (producto_id),
    CONSTRAINT uq_detalle_pedido_producto UNIQUE (pedido_id, producto_id),
    CONSTRAINT chk_detalle_cantidad_positiva CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_precio_positivo CHECK (precio_unitario > 0),
    CONSTRAINT chk_detalle_descuento
        CHECK (descuento_linea IS NULL OR descuento_linea BETWEEN 0 AND 100)
);

INSERT INTO clientes
    (nombre_completo, email, telefono, ciudad, fecha_registro, activo)
VALUES
    ('Ana Torres',       'ana.torres@example.com',       '999111001', 'Lima',       '2024-10-03', TRUE),
    ('Carlos Mendoza',   'carlos.mendoza@example.com',   '999111002', 'Arequipa',   '2024-10-15', TRUE),
    ('Luisa Fernandez',  'luisa.fernandez@example.com',  NULL,        'Lima',       '2024-11-02', TRUE),
    ('Jorge Ramirez',    'jorge.ramirez@example.com',    '999111004', 'Trujillo',   '2024-11-20', TRUE),
    ('Maria Quispe',     'maria.quispe@example.com',     '999111005', 'Cusco',      '2024-12-01', TRUE),
    ('Pedro Salazar',    'pedro.salazar@example.com',    NULL,        'Piura',      '2024-12-08', TRUE),
    ('Sofia Rojas',      'sofia.rojas@example.com',      '999111007', 'Lima',       '2024-12-19', TRUE),
    ('Diego Castro',     'diego.castro@example.com',     '999111008', NULL,         '2025-01-04', TRUE),
    ('Valeria Paredes',  'valeria.paredes@example.com',  '999111009', 'Chiclayo',   '2025-01-07', TRUE),
    ('Andres Herrera',   'andres.herrera@example.com',   NULL,        'Lima',       '2025-01-15', TRUE),
    ('Camila Vega',      'camila.vega@example.com',      '999111011', 'Huancayo',   '2025-02-01', TRUE),
    ('Ricardo Flores',   'ricardo.flores@example.com',   '999111012', 'Arequipa',   '2025-02-09', TRUE),
    ('Daniela Silva',    'daniela.silva@example.com',    NULL,        NULL,         '2025-02-18', TRUE),
    ('Miguel Navarro',   'miguel.navarro@example.com',   '999111014', 'Ica',        '2025-03-02', TRUE),
    ('Elena Campos',     'elena.campos@example.com',     '999111015', 'Lima',       '2025-03-10', FALSE);

INSERT INTO productos
    (nombre_producto, categoria, precio_lista, costo_unitario, activo)
VALUES
    ('Laptop Pro 14',        'Tecnologia',  3200.00, 2450.00, TRUE),
    ('Smartphone X',         'Tecnologia',  1800.00, 1320.00, TRUE),
    ('Monitor 27 pulgadas',  'Electronica',  950.00,  650.00, TRUE),
    ('Audifonos Bluetooth',  'Electronica',  350.00,  210.00, TRUE),
    ('Cafetera Programable', 'Hogar',         420.00,  270.00, TRUE),
    ('Aspiradora Compacta',  'Hogar',         780.00,  510.00, TRUE),
    ('Silla Ergonomica',     'Oficina',       650.00,  430.00, TRUE),
    ('Lampara de Escritorio','Oficina',       180.00,   95.00, TRUE),
    ('Mouse Inalambrico',    'Accesorios',    120.00,   60.00, TRUE),
    ('Teclado Mecanico',     'Accesorios',    280.00,  155.00, TRUE),
    ('Hub USB-C',            'Accesorios',     90.00,   42.00, TRUE),
    ('Impresora Multifuncion','Electronica', 1100.00,  760.00, TRUE);

INSERT INTO pedidos
    (cliente_id, fecha_pedido, estado, canal_venta, descuento_pedido, fecha_entrega)
VALUES
    (1,  '2025-01-05 09:15', 'completado', 'web',         NULL, '2025-01-08'),
    (2,  '2025-01-08 18:30', 'completado', 'app',         5.00, '2025-01-11'),
    (3,  '2025-01-12 11:20', 'completado', 'web',         NULL, '2025-01-16'),
    (1,  '2025-01-18 16:45', 'completado', 'app',        10.00, '2025-01-21'),
    (4,  '2025-01-24 10:05', 'cancelado',  'web',         NULL, NULL),
    (5,  '2025-01-28 14:10', 'completado', 'marketplace', NULL, '2025-02-02'),
    (6,  '2025-02-03 08:50', 'completado', 'app',         NULL, '2025-02-06'),
    (7,  '2025-02-07 19:35', 'completado', 'web',         5.00, '2025-02-10'),
    (2,  '2025-02-11 12:40', 'completado', 'web',         NULL, '2025-02-14'),
    (8,  '2025-02-16 15:25', 'completado', 'marketplace', NULL, '2025-02-21'),
    (9,  '2025-02-21 17:00', 'completado', 'app',         NULL, '2025-02-25'),
    (3,  '2025-02-26 10:30', 'completado', 'web',         5.00, '2025-03-02'),
    (10, '2025-03-04 09:05', 'completado', 'web',         NULL, '2025-03-07'),
    (1,  '2025-03-09 13:50', 'completado', 'app',         NULL, '2025-03-12'),
    (11, '2025-03-13 18:15', 'completado', 'marketplace', NULL, '2025-03-18'),
    (12, '2025-03-17 11:45', 'completado', 'web',        10.00, '2025-03-20'),
    (5,  '2025-03-23 16:20', 'completado', 'app',         NULL, '2025-03-27'),
    (13, '2025-03-29 20:10', 'cancelado',  'web',         NULL, NULL),
    (14, '2025-04-02 08:40', 'completado', 'app',         NULL, '2025-04-05'),
    (2,  '2025-04-06 14:55', 'completado', 'web',         5.00, '2025-04-09'),
    (15, '2025-04-11 10:25', 'completado', 'marketplace', NULL, '2025-04-16'),
    (6,  '2025-04-15 17:35', 'completado', 'web',         NULL, '2025-04-18'),
    (7,  '2025-04-21 12:10', 'completado', 'app',         NULL, '2025-04-24'),
    (1,  '2025-04-27 19:05', 'enviado',    'web',        10.00, NULL),
    (8,  '2025-05-03 09:45', 'completado', 'marketplace', NULL, '2025-05-08'),
    (9,  '2025-05-08 15:30', 'completado', 'web',         NULL, '2025-05-11'),
    (3,  '2025-05-12 18:55', 'completado', 'app',         5.00, '2025-05-15'),
    (10, '2025-05-18 11:15', 'completado', 'web',         NULL, '2025-05-22'),
    (11, '2025-05-24 13:40', 'completado', 'app',         NULL, '2025-05-27'),
    (12, '2025-05-29 16:05', 'completado', 'marketplace', 5.00, '2025-06-03'),
    (13, '2025-06-02 10:50', 'completado', 'web',         NULL, '2025-06-05'),
    (14, '2025-06-07 14:20', 'completado', 'app',         NULL, '2025-06-10'),
    (15, '2025-06-13 09:30', 'completado', 'web',         5.00, '2025-06-17'),
    (1,  '2025-06-18 18:10', 'completado', 'marketplace', NULL, '2025-06-23'),
    (2,  '2025-06-23 12:25', 'enviado',    'app',        10.00, NULL),
    (5,  '2025-06-28 17:45', 'completado', 'web',         NULL, '2025-07-02');

INSERT INTO detalle_pedido
    (pedido_id, producto_id, cantidad, precio_unitario, descuento_linea)
VALUES
    (1,  1,  1, 3200.00, NULL), (1,  9, 1, 120.00, NULL),
    (2,  2,  1, 1800.00, 5.00), (2,  4, 1, 350.00, NULL),
    (3,  7,  1,  650.00, NULL), (3,  8, 2, 180.00, 10.00),
    (4,  1,  1, 3200.00, 15.00), (4, 10, 1, 280.00, NULL),
    (5,  6,  1,  780.00, NULL), (5,  5, 1, 420.00, NULL),
    (6,  3,  1,  950.00, NULL), (6, 10, 2, 280.00, 5.00),
    (7,  2,  1, 1800.00, NULL), (7,  9, 2, 120.00, NULL),
    (8,  7,  2,  650.00, 5.00), (8,  8, 1, 180.00, NULL),
    (9,  1,  1, 3200.00, NULL), (9, 11, 2,  90.00, NULL),
    (10, 6,  1,  780.00, NULL), (10, 8, 2, 180.00, NULL),
    (11, 4,  2,  350.00, NULL), (11, 9, 1, 120.00, NULL),
    (12, 12, 1, 1100.00, 10.00), (12, 10, 1, 280.00, NULL),
    (13, 3,  2,  950.00, 5.00), (13, 9, 2, 120.00, NULL),
    (14, 1,  1, 3200.00, NULL), (14, 3, 1, 950.00, 10.00),
    (15, 7,  1,  650.00, NULL), (15, 10, 2, 280.00, NULL),
    (16, 2,  2, 1800.00, 10.00), (16, 4, 1, 350.00, NULL),
    (17, 6,  1,  780.00, NULL), (17, 5, 1, 420.00, NULL),
    (18, 1,  1, 3200.00, NULL), (18, 12, 1, 1100.00, NULL),
    (19, 8,  3,  180.00, NULL), (19, 9, 3, 120.00, 5.00),
    (20, 1,  1, 3200.00, 5.00), (20, 10, 1, 280.00, NULL),
    (21, 2,  1, 1800.00, NULL), (21, 11, 1,  90.00, NULL),
    (22, 12, 1, 1100.00, NULL), (22, 9, 2, 120.00, NULL),
    (23, 7,  2,  650.00, NULL), (23, 8, 2, 180.00, NULL),
    (24, 1,  1, 3200.00, 10.00), (24, 4, 2, 350.00, 5.00),
    (25, 6,  2,  780.00, 5.00), (25, 9, 1, 120.00, NULL),
    (26, 3,  1,  950.00, NULL), (26, 10, 1, 280.00, NULL),
    (27, 2,  1, 1800.00, 5.00), (27, 4, 2, 350.00, NULL),
    (28, 7,  1,  650.00, NULL), (28, 8, 3, 180.00, NULL),
    (29, 1,  1, 3200.00, NULL), (29, 11, 2,  90.00, NULL),
    (30, 12, 1, 1100.00, 5.00), (30, 10, 1, 280.00, NULL),
    (31, 5,  2,  420.00, NULL), (31, 8, 1, 180.00, NULL),
    (32, 2,  1, 1800.00, NULL), (32, 9, 2, 120.00, 5.00),
    (33, 3,  2,  950.00, 10.00), (33, 4, 1, 350.00, NULL),
    (34, 1,  1, 3200.00, 5.00), (34, 7, 1, 650.00, NULL),
    (35, 2,  2, 1800.00, 10.00), (35, 10, 2, 280.00, 5.00),
    (36, 6,  1,  780.00, NULL), (36, 5, 1, 420.00, 10.00);

-- Validaciones rapidas: confirman que el dataset minimo fue cargado completo.
SELECT COUNT(*) AS total_clientes FROM clientes;
SELECT COUNT(*) AS total_productos FROM productos;
SELECT COUNT(*) AS total_pedidos FROM pedidos;
SELECT COUNT(*) AS total_lineas_pedido FROM detalle_pedido;
